library(ggplot2)


# Define UI for application that estimates probability of heart disease
shinyUI(fluidPage(
  tags$style('.container-fluid {
                             background-color: #FFFFFF;
              }'),
  # Application title
  titlePanel("Shiny R Test"),
  
  sidebarLayout(
    sidebarPanel(
      numericInput(inputId ="age", label = "Age?", value = 0, min = 1, max = 100),
      selectizeInput(inputId = "sex",
                     label = "What is your sex?",
                     choices = c('Male','Female')),
      numericInput(inputId ="bmi", label = "What is your BMI?", value = 24, min = 12, max = 60),
      selectizeInput(inputId = "hyp",
                     label = "Hypertension?",
                     choices = c("No","Yes")),
      selectizeInput(inputId = "afib",
                     label ="Atrialfibrilation",
                     choices = c("No","Yes")),
      selectizeInput(inputId = "chd",
                     label = "chd with no MI",
                     choices = c("No","Yes")),
      selectizeInput(inputId = "diab",
                     label = "Diabetes",
                     choices = c("No","Yes")),
      selectizeInput(inputId = "defane",
                     label = "Deficiency Anemias",
                     choices = c("No","Yes")),
      selectizeInput(inputId = "depre",
                     label = "Depression",
                     choices = c("No","Yes")),
      selectizeInput(inputId = "hyperl",
                     label = "Hyperlipemia",
                     choices = c("No","Yes")),
      selectizeInput(inputId = "renfail",
                     label = "Reanl Failure",
                     choices = c("No","Yes")),
      selectizeInput(inputId = "copd",
                     label = "COPD",
                     choices = c("No","Yes")),
      numericInput(inputId = "hrate",
                   label = "HeartRate",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "syst",
                   label = "Systolic",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "dias",
                   label = "Disatolic",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "resp",
                   label = "Respiratory Rate",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "temp",
                   label = "temperature",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "spo2",
                   label = "SPO2",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "urine",
                   label = "Urine Output",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "hema",
                   label = "Hematocrit",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "rbc",
                   label = "RBC",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "mch",
                   label = "MCH",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "mchc",
                   label = "MCHC",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "mcv",
                   label = "MCV",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "rdw",
                   label = "RDW",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "leu",
                   label = "Leucocyte",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "plate",
                   label = "Platelets",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "neu",
                   label = "Neutrophils",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "bas",
                   label = "Basophils",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "lym",
                   label = "Lymphocites",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "pt",
                   label = "PT",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "inr",
                   label = "INR",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "nt",
                   label = "NTPROBNP",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "creak",
                   label = "Creatine Kinase",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "crea",
                   label = "Creatinine",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "urea",
                   label = "Urea Nitro",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "gluc",
                   label = "Glucose",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "bpot",
                   label = "Blood Potasium",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "bsod",
                   label = "Blood Sodium",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "bcalc",
                   label = "Blood Calcium",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "chlo",
                   label = "Chloride",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "agap",
                   label = "Anion Gap",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "mag",
                   label = "Magnesium",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "ph",
                   label = "PH",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "bica",
                   label = "Bicarbonate",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "lacid",
                   label = "Lactic Acid",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "pco2",
                   label = "PCO2",
                   value = 0, min = 0, max = 1000),
      numericInput(inputId = "ef",
                   label = "EF",
                   value = 0, min = 0, max = 1000)

    ),
    
    # Display the probability of heart disease
    mainPanel(
      HTML(' '),
      tabPanel("Description", 
               textOutput("description")
      ),
      actionButton("calculate", "Calculate"),
      tabPanel("probability_hd",
               textOutput("prob_hd")
      ),
     
      
      
    )
  )
))



#################
